- hosts: smsforward

  tasks:

  - name: add nodesource key
    apt_key: 
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

  - name: Add nodesource repo
    apt_repository:
      repo: deb https://deb.nodesource.com/node_11.x xenial main
      state: present

  - name: install nodejs
    apt:
      name: 'nodejs'
      state: present

  - name: install serverless
    npm:
      name: serverless
      global: yes

  - name: verify required files
    stat:
      path: '{{ item }}'
    with_items:
      - '/home/vagrant/.aws/credentials'
      - '/home/vagrant/flowroute-sms-forward/config.py'