- hosts: smsforward

  tasks:

  - name: add apt key for nodesource
    apt_key: 
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

  - name: add repo for nodesource
    apt_repository:
      repo: deb https://deb.nodesource.com/node_11.x xenial main
      state: present

  - name: install packages
    apt:
      name: 'nodejs'
      state: present

  - name: Install serverless
    npm:
      name: serverless
      global: yes

  - name: sls info
    command: sls info
    args:
      chdir: /home/vagrant/flowroute-sms-forward